# -*- coding: utf-8 -*-
"""House_Prize.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dywzb_tJtRCRWeSmaQQTPkYmI9_F6osm
"""

# import google libraries
from google.colab import drive
drive.mount('/content/drive')

# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

# reading the dataset
dataset= pd.read_csv('/content/drive/My Drive/Colab Notebooks/linear_house_prize/house_prize.csv')

dataset

# %matplotlib inline
plt.scatter(dataset.Areaofhouse,dataset.priceofhouse)

# pottted charts on Xlabel as indepenedent variable and Ylablel as Depenendent varible
# %matplotlib inline
plt.xlabel('HouseofArea(square ft)')
plt.ylabel('HouseofPrice(INR)')
plt.scatter(dataset.Areaofhouse,dataset.priceofhouse,color='red',marker='+')

# create a object of LinerReegression model

linear_reg_model= linear_model.LinearRegression()

# Fit the Training Model
linear_reg_model.fit(dataset[['Areaofhouse']],dataset.priceofhouse)

# ready to predict,
# I am going predict 3500 sq ft price

linear_reg_model.predict([[3500]])

# Liner Formula = Y=MX+ B
# Where X-> Slope and B intercept


linear_reg_model.coef_

"""![alt text](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTE4hCxKDih-9Yuy8vwnqaCIILssTlU8pb1SjuBMbdZKaagBpbeAw))"""

# to get intercept
linear_reg_model.intercept_



# Formula is 

# Y = mx + b

# m=30.35714286 (this is coef_)
# b=455000       (This is intercept_)
# x=3500          (Input value)

# Now am going to sum of all vlaues to match with predicted values

# Predicted Value for 3500 SQ ft = 561250

#formula through

result = 135.78767123*3500+180616.43835616432
result

# check both are equal values

